name: tests
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install virtualenv
          python -m venv .env
          source .env/bin/activate
          python -m pip install -r requirements.txt
      - name: Run tests
        run: |
          source .env/bin/activate
          python test_runner.py
